image: python:3.6

stages:
  - test
  - kill

.job-template: &gravedigger
  before_script:
    - pip install pipenv
    - pipenv install
  script:
    - pipenv run python gravedigger/gravedigger.py
  artifacts:
    paths:
      - gravedigger.log
    expire_in: 1 week

# -----------------------------------------------------------------------------

test:
  stage: test
  before_script:
    - pip install pipenv
    - pipenv install --dev
  script:
    - pipenv run py.test gravedigger/tests.py

clean_10c:
  stage: kill
  <<: *gravedigger
  tags:
    - 10c
    
clean_40c:
  stage: kill
  <<: *gravedigger
  tags:
    - 40c
    
clean_8c:
  stage: kill
  <<: *gravedigger
  tags:
    - 8c


