.job-template: &gravedigger
  image: python:3.6
  before_script:
    - pip install pipenv
    - pipenv install
  script:
    - pipenv run python gravedigger/gravedigger.py
  artifacts:
    paths:
      - gravedigger.log.txt
    expire_in: 1 week

# -----------------------------------------------------------------------------

clean_10c:
  <<: *gravedigger
  tags:
    - 10c
