clean_runner:
  tags:
    - $TARGET_RUNNER
  image: python:3.6-alpine
  script:
    - pipenv install
    - pipenv run python gravedigger/gravedigger.py
  artifacts:
    paths:
      - gravedigger.log
    expire_in: 1 week

